DROP TABLE if exists bookmarks;

CREATE TABLE bookmarks (
  title TEXT NOT NULL,
  id INTEGER PRIMARY KEY generated by default as identity,
  url TEXT NOT NULL, 
  description TEXT,
  rating INTEGER
);

INSERT into bookmarks (title, url, rating, description) values
('Thinkful', 'www.thinkful.com', 2, 'bootcamp'),
('Google', 'www.google.com', 4, 'search'),
('codecademy', 'www.codecamdemy.com', 4, 'code tutorials/walkthroughs'),
('udemy', 'www.udemy.com', 4, 'learn with cheap courses'),
('youtube', 'www.youtube.com', 4, 'free video tutorials'),
('launch school', 'www.launchschool.com', 4, 'master fundamentals'),
('Structure and interpretation of computer programs',  'https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-4.html', 4, 'compsci text'),
('Nand2Tetris','https://www.coursera.org/learn/build-a-computer', 4, 'learn how to build a computer'),
('Eloquent JavaScript', 'https://eloquentjavascript.net/', 5, 'JavaScript textbook'),
('Speaking JavaScript', 'http://speakingjs.com/es5/index.html', 4, 'JavaScript textbook');